# Generated by Django 3.1.3 on 2020-12-16 15:00

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CkEditorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', utils.models.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='AuditImage', verbose_name='immagine')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creato')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificato')),
            ],
            options={
                'verbose_name': 'Immagine ckeditor',
                'verbose_name_plural': 'Immagini ckeditor',
            },
        ),
    ]
